### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by flipdoubt** [vector-of-bool/vscode-gitflow#1]
Can't quite figure out how/where to make it do anything. Not even sure where to type "git flow init -d". A super quick Getting Started section in the read-me would go a long way to my kicking the tires to figure out where/how to contribute.

Cool idea though.

**Comment by flipdoubt** [comment]
Ah, I need to type that darn greater than sign to get started:

> After typing CMD-P or CTRL-P to open Code's command line, type the following for a list of GitFlow commands:
> `> gitflow`
>
> For example, type the following to initialize a repository for GitFlow in the current directory:
> `> gitflow initialize`

**Comment by jitcoder** [comment]
this sounds more like a user issue rather than an issue with the plugin.

If you're using the latest version of visual studio code, 

if you press CMD+SHIFT+P, you can simply type in "gitflow" (without the quotes), and then select the option you'd like to use, using the arrow keys (or continue typing out the command)

no need to type in ">"

Can this issue be closed?
